### ISSUE TITLE
Why resize()?

### ISSUE THREAD

**Issue by krustchinsky** [CSCE360025/Project#15]
Resize is only useful if we have existing data in the container (it re-sizes an already used container) so I don't think we need to do this. From what I understand the only thing we need to do regarding number of cache lines is to calculate the index where a specific memory address would be cached. Once this is calculated I don't think we need to simulate a fixed cache size as that would require us to use a dynamically allocated array of some sort.

So I'm going to remove this is at seems to be serving no purpose right now. If you bring it into the debugger and set some watches you will see the resize() takes the empty vector and expands it, but then returns an empty vector, because nothing is actually in the container.

See this: http://www.cplusplus.com/reference/vector/vector/resize/

**Comment by T-King** [comment]
Resize was there because we need to have the actual size of the cache to which to index. The name is not very accurate, I admit, since we only use it one time (the initial use in the constructor) but that's the most logical way to do it I think because we won't know the size of the cache until runtime.

**Comment by T-King** [comment]
All of that said, unfortunately I am still really struggling to understand how caching works, so I may be implementing things erroneously.
