### ISSUE TITLE
questions in createCacheLine

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#17]
How are we using "to_string()"? When I looked it up and tried it, I was under the impression that required a more up-to-date compiler to use. Also, is it necessary to clear the stringstream buffer if it is deleted after the function call? It's not like we're reusing it.

**Comment by krustchinsky** [comment]
to_string() is in the C++11 standard (kinda), and g++ does some feature detection so it should work on most systems. I'm adding the -std=c++11 to the Makefile just in case. It is necessary to clear the string stream buffer because it stores things in memory in a strange way (read more on that) so to prevent any oddities I'm just clearing it when we no longer need it.
